# it should take the directory
# mapping-index: mapping indexes for bowtie2, bwa, hisat2, salmon, star
# annotation: gene annotation for hisat2, stringtie, cufflinks (.gtf, .gff, and .bed)
datasource:
  rna-seq:
    dir_path: /path/to/rna-seq/
    files:
      - LNCaP_DHT_RNA_rep1
      - LNCaP_DHT_RNA_rep2
      - LNCaP_Veh_RNA_rep1
      - LNCaP_Veh_RNA_rep2
    paired-end: y
    suffix: .fastq.gz
  chip-seq:
    dir_path: /path/to/chip-seq/
    files:
      - LNCaP_DHT_AR_1
      - LNCaP_DHT_AR_2
      - LNCaP_Veh_AR_1
      - LNCaP_Veh_AR_2
    paired-end: n
    suffix: .fastq.gz
  mapping-index: /path/to/mapping-index
  annotation: /path/to/annotation

resultdestination:
  rna-seq: /path/to/rna-seq-results
  chip-seq: /path/to/chip-seq-results
  joint-analysis: /path/to/joint-analysis-results
  modeling: /path/to/modeling-results
  log: /path/to/log

rnaseq:
  bowtie2:
    -p: 16
    -t: y

chipseq:
  hisat2:
    -p: 16

joint:
  fastqc:
    -f: fastq
  # .sam file conversion, sorting, indexing
  samtools:
    view:
      -b: y
      -S: y
      -@: 16
    sort:
      -@: 16
    index: y
